create table `{prefix}tickets` (
  `id` int(10) unsigned not null auto_increment,
  `tickno` varchar(250) not null default '',
  `ts` int(30) not null default '0',
  `lastrevision` int(30) not null default '0',
  `department` int(8) not null default '0',
  `assignedto` varchar(250) not null default '',
  `visitorID` int(8) not null default '0',
  `subject` varchar(250) not null default '',
  `mailBodyFilter` varchar(30) not null default '',
  `comments` text default null,
  `priority` varchar(250) not null default '',
  `ticketStatus` varchar(20) not null default '',
  `ipAddresses` varchar(250) not null default '',
  `ticketNotes` text default null,
  `isDisputed` enum('yes','no') not null default 'no',
  `disPostPriv` enum('yes','no') not null default 'yes',
  `source` varchar(10) not null default 'standard',
  `spamFlag` enum('yes','no') not null default 'no',
  `lockteam` int(7) not null default '0',
  `lockrelease` int(30) not null default '0',
  `worktime` varchar(50) not null default '00:00:00',
  primary key (`id`),
  key `depid_index` (`department`),
  key `pry_index` (`priority`),
  key `isdis_index` (`isDisputed`),
  key `ts_index` (`ts`),
  key `vis_index` (`visitorID`),
  key `lockteam` (`lockteam`),
  key `ticketStatus` (`ticketStatus`),
  key `tickno` (`tickno`)
) {engine}