create table `{prefix}users` (
  `id` int(5) not null auto_increment,
  `ts` int(30) not null default '0',
  `name` varchar(100) not null default '',
  `email` varchar(250) not null default '',
  `email2` text default null,
  `accpass` varchar(250) not null default '',
  `signature` text default null,
  `notify` enum('yes','no') not null default 'yes',
  `pageAccess` text default null,
  `emailSigs` enum('yes','no') not null default 'no',
  `notePadEnable` enum('yes','no') not null default 'yes',
  `delPriv` enum('yes','no') not null default 'no',
  `nameFrom` varchar(250) not null default '',
  `emailFrom` varchar(250) not null default '',
  `assigned` enum('yes','no') not null default 'no',
  `timezone` varchar(50) not null default '0',
  `enabled` enum('yes','no') not null default 'yes',
  `notes` text default null,
  `ticketHistory` enum('yes','no') not null default 'yes',
  `enableLog` enum('yes','no') not null default 'yes',
  `mailbox` enum('yes','no') not null default 'yes',
  `mailFolders` int(3) not null default '5',
  `mailDeletion` enum('yes','no') not null default 'yes',
  `mailScreen` enum('yes','no') not null default 'yes',
  `mailCopy` enum('yes','no') not null default 'yes',
  `mailPurge` int(3) not null default '0',
  `addpages` text default null,
  `mergeperms` enum('yes','no') not null default 'yes',
  `digest` enum('yes','no') not null default 'yes',
  `profile` enum('yes','no') not null default 'yes',
  `helplink` enum('yes','no') not null default 'no',
  `defDays` int(3) not null default '45',
  `editperms` text default null,
  `lock` enum('yes','no') not null default 'yes',
  `close` enum('yes','no') not null default 'yes',
  `admin` enum('yes','no') not null default 'no',
  `timer` enum('yes','no') not null default 'yes',
  `startwork` enum('yes','no') not null default 'yes',
  `workedit` enum('yes','no') not null default 'yes',
  `language` varchar(250) not null default 'english',
  `spamnotify` enum('yes','no') not null default 'yes',
  `savedstaff` text default null,
  `staffupnotify` enum('yes','no') not null default 'no',
  `faqHistory` enum('yes','no') not null default 'no',
  `digestops` text default null,
  `digestdays` text default null,
  primary key (`id`),
  key `email_index` (`email`),
  key `nty_index` (`notify`)
) {engine}